var constants = {
    btn: {
        ACCOUNT: 'Tài khoản',
        ACCOUNT_MANAGEMENT: 'Quản ký tài khoản',
        CANCEL: 'Hủy bỏ',
        CANCEL_ORDER: 'Hủy đơn hàng',
        CHANGE_PASSWORD: 'Đổi mật khẩu',
        CLOSE: 'Đóng',
        CREATE_ORDER: 'Tạo mới đơn hàng',
        DONE: 'Hoàn thành',
        EDIT: 'Sửa',
        LIST_ORDERS: 'Danh sách đơn hàng',
        LIST_SHIPPER_REGISTERED: 'Danh sách shipper đăng ký ({0})',
        LOGIN: 'Đăng nhập',
        LOGOUT: 'Thoát',
        MY_ORDERS: 'Đơn hàng của tôi',
        ORDER_MANAGEMENT: 'Quản lý đơn hàng',
        ORDER_REGISTER: 'Đăng ký đơn hàng',
        ORDER_REGISTERED: 'Đơn hàng đã đăng ký',
        ORDER_UNREGISTER: 'Hủy đăng ký đơn hàng',
        ORDER: 'Đơn hàng',
        PROFILE: 'Thông tin cá nhân',
        SAVE: 'Lưu lại',
        SELECT: 'Chọn',
        SHIPPER_INFO: 'Thông tin Shipper',
        SHOW_REVIEWS: 'Xem các đánh giá',
        SIGN_UP: 'Đăng ký',
        UPDATE: 'Cập nhật'
    },
    req: {
        LOGIN: 'login',
        ORDER: 'order',
        REGISTER: 'register',
        REVIEWS: 'reviews',
        SIGN_UP: 'signup',
        USER: 'user'
    },
    lbl: {
        ADVANCE_DEPOSIT: 'Đặt cọc',
        ALL_ITEMS: 'Tất cả đơn hàng',
        ALREADY_HAVE_ACCOUNT: 'Đã có tài khoản? <a href="login.html">Đăng nhập</a>.',
        AVERAGE_SCORE: 'Điểm trung bình:',
        BIRTH_DAY: 'Ngày sinh',
        CHANGE_PASSWORD: 'Thay đổi mật khẩu',
        CREATE_ORDER_SUCCESS: 'Tạo mới đơn hàng {0} thành công.',
        CURRENT_PASSWORD: 'Mật khẩu hiện tại',
        DESTINATION: 'Nơi giao hàng',
        EMAIL: 'Email',
        ERROR: 'An error has occurred.',
        ERROR_EMAIL_EXIST: 'Email đã tồn tại.',
        ERROR_PASSWORD_INCORRECT: 'Mật khẩu không đúng.',
        ERROR_PASSWORD_NOT_MATCH: 'Mật khẩu không khớp.',
        ERROR_USERNAME_EXIST: 'Tài khoản đã tồn tại.',
        ERROR_USERNAME_NOT_EXIST: 'Tài khoản không tồn tại.',
        FEMALE: 'Nữ',
        FORGOT_PASSWORD: 'Quên mật khẩu?',
        FULL_NAME: 'Họ tên',
        GENDER: 'Giới tính',
        HOUR: 'HH',
        INVALID_EMAIL: 'Email không hợp lệ.',
        LIST_REVIEWS: 'Các đánh giá',
        LOADING_LIST_ORDERS: 'Đang tải danh sách đơn hàng...',
        LOGIN: 'Đăng nhập',
        MALE: 'Nam',
        MINUTE: 'MM',
        NEW_PASSWORD: 'Mật khẩu mới',
        NOT_REGISTERED: 'Chưa có Shipper nào đăng ký đơn hàng này.',
        ORDER_NAME: 'Tên đơn hàng',
        ORDER_STATUS: 'Trạng thái:',
        PASSWORD: 'Mật khẩu',
        PASSWORD_CHANGED: 'Thay đổi mật khẩu thành công.',
        PERSONAL_INFO: 'Thông tin cá nhân',
        PHONE_NUMBER: 'Số điện thoại',
        PROFIT: 'Lợi nhuận',
        RE_PASSWORD: 'Nhập lại mật khẩu',
        RECIPIENTS_INFO: 'Thông tin người nhận:',
        RECIPIENTS_NAME: 'Tên người nhận',
        RECIPIENTS_PHONE_NUMBER: 'SĐT người nhận',
        REGISTER_ORDER_SUCCESS: 'Đăng ký đơn hàng {0} thành công, chờ chủ shop duyệt.',
        REQUIRED: 'Bắt buộc nhập.',
        REVIEWS: '{0} lượt đánh giá',
        SELECTED: 'Bạn đã chọn shipper {0} cho đơn hàng {1}.',
        SHIPPER: 'Shipper',
        SHIPPER_DONE: 'Shipper đã vận chuyển: {0}',
        SHIPPER_INFO: 'Thông tin của {0}',
        SHIPPER_SHIPPING: 'Shipper đang vận chuyển: {0}',
        SHOP: 'Shop',
        SHOP_ADDRESS: 'Địa chỉ cửa hàng',
        SHOP_INFO: 'Thông tin cửa hàng',
        SHOP_MANAGER: 'Chủ cửa hàng',
        SHOP_NAME: 'Tên cửa hàng',
        SIGN_UP: 'Đăng ký tài khoản',
        START_TIME: 'Thời gian giao hàng',
        STARTING_POINT: 'Nơi nhận hàng',
        STATUS_DONE: 'Đã hoàn thành',
        STATUS_CANCELED: 'Đã hủy',
        STATUS_EXPIRED: 'Hết thời gian',
        STATUS_SHIPPING: 'Đang vận chuyển',
        STATUS_WAITING: 'Đang chờ',
        UNREGISTER_ORDER_SUCCESS: 'Hủy đăng ký đơn hàng {0} thành công.',
        UPDATE_ORDER_SUCCESS: 'Cập nhật đơn hàng {0} thành công.',
        UPDATE_PROFILE_SUCCESS: 'Cập nhật tài khoản thành công.',
        USER_TYPE: 'Loại tài khoản',
        USERNAME: 'Tên tài khoản',
        WELCOME: 'Xin chào'
    },
    color: {
        CANCELED: 'grey-300',
        DONE: 'light-green-100',
        EXPIRED: 'red-100',
        SHIPPING: 'cyan-100',
        UNKNOWN: 'grey-A100',
        WAITING: 'yellow-100'
    },
    title: {
        CHANGE_PASSWORD: 'Đổi mật khẩu',
        CREATE_ORDER: 'Tạo mới đơn hàng',
        LIST_ORDERS: 'Danh sách đơn hàng',
        LOGIN: 'Đăng nhập',
        ORDER_INFO: 'Thông tin đơn hàng',
        ORDER_MANAGEMENT: 'Quản lý đơn hàng',
        ORDER_REGISTERED: 'Đơn hàng đã đăng ký',
        PROFILE: 'Thông tin tài khoản',
        REVIEWS_SHIPPER: 'Đánh giá shipper {0} cho đơn hàng {1}',
        SELECT_SHIPPER: 'Lựa chọn shipper ({0})',
        SHIPPER_INFO: 'Thông tin shipper ({0})',
        SIGN_UP: 'Đăng ký thành viên',
        UPDATE_ORDER: 'Cập nhật đơn hàng'
    }
};
