var constants = {
    btn: {
        ACCOUNT_MANAGEMENT: 'Quản ký tài khoản',
        CANCEL: 'Hủy bỏ',
        CHANGE_PASSWORD: 'Đổi mật khẩu',
        CLOSE: 'Đóng',
        LOGIN: 'Đăng nhập',
        LOGOUT: 'Thoát',
        MY_ORDERS: 'Đơn hàng của tôi',
        ORDER_MANAGEMENT: 'Quản lý đơn hàng',
        ORDER_REGISTER: 'Đăng ký đơn hàng',
        PROFILE: 'Thông tin cá nhân',
        SAVE: 'Lưu lại',
        SIGN_UP: 'Đăng ký'
    },
    lbl: {
        ADVANCE_DEPOSIT: 'Đặt cọc',
        ALREADY_HAVE_ACCOUNT: 'Đã có tài khoản? <a href="login.html">Đăng nhập</a>.',
        DESTINATION: 'Nơi giao hàng',
        EMAIL: 'Email',
        ERROR_EMAIL_EXIST: 'Email đã tồn tại.',
        ERROR_USERNAME_EXIST: 'Tài khoản đã tồn tại.',
        ERROR_USERNAME_NOT_EXIST: 'Tài khoản không tồn tại.',
        FORGOT_PASSWORD: 'Quên mật khẩu?',
        FULL_NAME: 'Họ tên',
        INVALID_EMAIL: 'Email không hợp lệ.',
        LOGIN: 'Đăng nhập',
        ORDER_NAME: 'Tên đơn hàng',
        PASSWORD: 'Mật khẩu',
        PASSWORD_INCORRECT: 'Mật khẩu không đúng.',
        PASSWORD_NOT_MATCH: 'Mật khẩu không khớp.',
        PHONE_NUMBER: 'Số điện thoại',
        PROFIT: 'Lợi nhuận',
        RE_PASSWORD: 'Nhập lại mật khẩu',
        RECIPIENTS_NAME: 'Tên người nhận',
        RECIPIENTS_PHONE_NUMBER: 'SĐT người nhận',
        REQUIRED: 'Bắt buộc nhập.',
        SHIPPER: 'Shipper',
        SHOP: 'Shop',
        SHOP_MANAGER: 'Chủ cửa hàng',
        SIGN_UP: 'Đăng ký tài khoản',
        START_TIME: 'Thời gian giao hàng',
        STARTING_POINT: 'Nơi nhận hàng',
        USERNAME: 'Tên tài khoản',
        WELCOME: 'Xin chào'
    },
    title: {
        CREATE_ORDER: 'Tạo mới đơn hàng',
        LOGIN: 'Đăng nhập',
        SIGN_UP: 'Đăng ký thành viên'
    }
};
