//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipping.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string OrderName { get; set; }
        public int ShopId { get; set; }
        public string StartingPoint { get; set; }
        public string Destination { get; set; }
        public System.DateTime StartTime { get; set; }
        public string RecipientsName { get; set; }
        public string RecipientsPhoneNumber { get; set; }
        public decimal AdvanceDeposit { get; set; }
        public decimal Profit { get; set; }
        public Nullable<int> SelectedShipperId { get; set; }
        public int Status { get; set; }
    }
}
