//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipping.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewsShipper
    {
        public int OrderId { get; set; }
        public int Score { get; set; }
        public string Content { get; set; }
        public System.DateTime RevTime { get; set; }
    }
}
