//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipping.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingRegistration
    {
        public int OrderId { get; set; }
        public int ShipperId { get; set; }
        public System.DateTime RegTime { get; set; }
    }
}
